# shared/config.py

CARPETAS_EXCLUIDAS: set[str] = {
    "__pycache__",
    ".git",
    ".venv",
    "venv",
    "env",
    ".env",
    "node_modules",
    ".dart_tool",
    ".idea",
    ".vscode",
    "build",
    "dist",
    "out",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    "coverage",
    ".coverage",
    "htmlcov",
    ".tox",
    "eggs",
    ".eggs",
    "*.egg-info",
}

EXTENSIONES_SOPORTADAS: dict[str, str] = {
    ".py":  "python",
    ".dart": "dart",
    ".js":  "js",
    ".jsx": "jsx",
    ".ts":  "ts",
    ".tsx": "tsx",
    ".c":   "c",
    ".h":   "c",
    ".cpp": "cpp",
    ".cc":  "cpp",
    ".cxx": "cpp",
    ".hpp": "cpp",
}

LLAMADAS_EXCLUIDAS: set[str] = {
    # built-ins Python
    "print",
    "len",
    "str",
    "int",
    "float",
    "bool",
    "list",
    "dict",
    "set",
    "tuple",
    "range",
    "enumerate",
    "zip",
    "map",
    "filter",
    "sorted",
    "reversed",
    "isinstance",
    "issubclass",
    "getattr",
    "setattr",
    "hasattr",
    "delattr",
    "callable",
    "open",
    "type",
    "repr",
    "id",
    "hash",
    "abs",
    "round",
    "min",
    "max",
    "sum",
    "any",
    "all",
    "next",
    "iter",
    "vars",
    "dir",
    "help",
    "super",
    "object",
    "property",
    "staticmethod",
    "classmethod",
    # control flow — no son llamadas reales
    "if",
    "for",
    "while",
    "return",
    "yield",
    "raise",
    "assert",
    "del",
    "pass",
    "break",
    "continue",
    "import",
    "from",
    "with",
    "try",
    "except",
    "finally",
    "else",
    "elif",
    "lambda",
    "await",
    "async",
    # dart/js/c comunes
    "print",
    "console",
    "require",
    "define",
    "include",
    "sizeof",
    "typeof",
    "instanceof",
    "void",
    "new",
    "delete",
    "throw",
    "catch",
    "switch",
    "case",
    "default",
}